# Generated by Django 5.1.2 on 2024-10-11 04:25

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[(task.models.PriorityEnum['LOW'], 'Low'), (task.models.PriorityEnum['MEDIUM'], 'Medium'), (task.models.PriorityEnum['HIGH'], 'High')], default=task.models.PriorityEnum['LOW'], max_length=10)),
                ('status', models.CharField(choices=[(task.models.StatusEnum['PENDING'], 'Pending'), (task.models.StatusEnum['IN_PROGRESS'], 'In Progress'), (task.models.StatusEnum['COMPLETED'], 'Completed')], default=task.models.StatusEnum['PENDING'], max_length=15)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
