# Generated by Django 5.1.2 on 2024-10-11 06:03

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(task.models.PriorityEnum['LOW'], 'Low'), (task.models.PriorityEnum['MEDIUM'], 'Medium'), (task.models.PriorityEnum['HIGH'], 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(task.models.StatusEnum['PENDING'], 'Pending'), (task.models.StatusEnum['IN_PROGRESS'], 'In Progress'), (task.models.StatusEnum['COMPLETED'], 'Completed')], default='Pending', max_length=15),
        ),
    ]
